"""phase d: assets and expenses

Revision ID: 07bfdd5b572b
Revises: b24bec32fb4a
Create Date: 2026-02-03 09:21:16.224986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bfdd5b572b'
down_revision = 'b24bec32fb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customers_pppoe_username'), type_='unique')
        batch_op.create_index(batch_op.f('ix_customers_pppoe_username'), ['pppoe_username'], unique=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_active_hotspot_username'), postgresql_where="(((service_type)::text = 'hotspot'::text) AND ((status)::text = 'active'::text) AND (hotspot_username IS NOT NULL))")
        batch_op.drop_index(batch_op.f('uq_active_pppoe_username'), postgresql_where="(((service_type)::text = 'pppoe'::text) AND ((status)::text = 'active'::text) AND (pppoe_username IS NOT NULL))")
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_service_type'), ['service_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_service_type'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))
        batch_op.create_index(batch_op.f('uq_active_pppoe_username'), ['pppoe_username'], unique=True, postgresql_where="(((service_type)::text = 'pppoe'::text) AND ((status)::text = 'active'::text) AND (pppoe_username IS NOT NULL))")
        batch_op.create_index(batch_op.f('uq_active_hotspot_username'), ['hotspot_username'], unique=True, postgresql_where="(((service_type)::text = 'hotspot'::text) AND ((status)::text = 'active'::text) AND (hotspot_username IS NOT NULL))")

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_pppoe_username'))
        batch_op.create_unique_constraint(batch_op.f('uq_customers_pppoe_username'), ['pppoe_username'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
