"""phase d: create assets and expenses tables

Revision ID: 8fcb7fc1cc37
Revises: 07bfdd5b572b
Create Date: 2026-02-03 10:10:00.368840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcb7fc1cc37'
down_revision = '07bfdd5b572b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('serial_number', sa.String(length=80), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='in_store', nullable=False),
    sa.Column('assigned_customer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_location_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['assigned_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', name='uq_assets_serial_number')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_assigned_customer_id'), ['assigned_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    op.create_table('asset_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performed_by_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_admin'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_events_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_events_performed_by_admin'), ['performed_by_admin'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('incurred_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_admin'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_incurred_at'), ['incurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_recorded_by_admin'), ['recorded_by_admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_recorded_by_admin'))
        batch_op.drop_index(batch_op.f('ix_expenses_incurred_at'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_at'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_index(batch_op.f('ix_expenses_asset_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('asset_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_events_performed_by_admin'))
        batch_op.drop_index(batch_op.f('ix_asset_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_asset_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_events_asset_id'))

    op.drop_table('asset_events')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_assigned_customer_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    # ### end Alembic commands ###
